// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr4XsjC3LQ27N5PKiqisOzWHaz_0oIbLs',
    appId: '1:636416413312:android:dddb14337eac702d73a065',
    messagingSenderId: '636416413312',
    projectId: 'flutter-devcamp-ui-e2a7d',
    storageBucket: 'flutter-devcamp-ui-e2a7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX6HBpku8ihmBwJ3FKwosaObSjNgpG-Yw',
    appId: '1:636416413312:ios:58cc2e7d89a8175d73a065',
    messagingSenderId: '636416413312',
    projectId: 'flutter-devcamp-ui-e2a7d',
    storageBucket: 'flutter-devcamp-ui-e2a7d.appspot.com',
    iosBundleId: 'com.example.flutterDevcampUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX2Gff2OSyhsfJZ1p0SEesp6a-pR00JdA',
    appId: '1:636416413312:web:f2a588191b7b03ba73a065',
    messagingSenderId: '636416413312',
    projectId: 'flutter-devcamp-ui-e2a7d',
    authDomain: 'flutter-devcamp-ui-e2a7d.firebaseapp.com',
    storageBucket: 'flutter-devcamp-ui-e2a7d.appspot.com',
  );
}
